### ISSUE TITLE
Exception in subscribtion

### ISSUE THREAD

**Issue by escamoteur** [nhost/nhost-dart#28]
After it seems that we have fixed with all subscription errors, yesterday the update of our Donation tracker stopped with this debug output:

```
[ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: type '(dynamic) => Map<String, dynamic>?' is not a subtype of type '(dynamic) => FutureOr<Map<String, dynamic>>?' of 'function result'
#0      WebSocketLink._parseSocketMessage (package:gql_websocket_link/src/link.dart)
package:gql_websocket_link/src/link.dart:1
#1      WebSocketLink._connect.<anonymous closure>
package:gql_websocket_link/src/link.dart:206
#2      WebSocketLink._connect.<anonymous closure>
package:gql_websocket_link/src/link.dart:201
#3      _rootRunUnary (dart:async/zone.dart:1436:47)
#4      _CustomZone.runUnary (dart:async/zone.dart:1335:19)
#5      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
#6      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#7      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#8      _rootRunUnary (dart:async/zone.dart:1436:47)
#9      _CustomZone.runUnary (dart:async/zone.dart:1335:19)
#10     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
#11     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#12     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#13     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)
#14     _StreamController._add (dart:async/stream_controller.dart:607:7)
#15     _rootRunUnary (dart:async/zone.dart:1436:47)
#16     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
#17     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
#18     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#19     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#20     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:733:19)
```

**Comment by shyndman** [comment]
I suspect this is because of the pinned alpha gql version we have in donation_tracker's pubspec.

Everything's in stable now. I'll send a pull.

**Comment by shyndman** [comment]
Yup, looks like that's all it was. I sent a PR.
